name: Build and Deploy React App to S3

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch (you can change this as needed)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Use the version of Node.js you need

    # Install dependencies and build the React app
    - name: Install dependencies and build the app
      run: |
        cd client  # Change to the directory where your React app is located
        npm install
        npm run build

    # Configure AWS CLI and authenticate using OIDC
    - name: Configure AWS CLI
      run: |
        aws --version  # Check AWS CLI version for debugging

    - name: AWS OIDC Authentication
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::544234170512:role/GithubRole  # Replace with your role ARN
        aws-region: us-east-1  # Modify the region as needed

    # Sync build output to S3 bucket
    - name: Deploy to S3
      run: |
        aws s3 sync client/build/ s3://dev-static-website-12345/ --delete

    # Optionally invalidate CloudFront (if you're using CloudFront)
    # - name: Invalidate CloudFront cache
    #   run: |
    #     aws cloudfront create-invalidation --distribution-id <your-cloudfront-id> --paths "/*"
