
name: React App Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build React app
        run: npm run build
      
      - name: AWS OIDC Authentication
        uses: aws-actions/configure-aws-credentials@v1
        with:
         role-to-assume: arn:aws:iam::544234170512:role/GithubRole  # Replace with your role ARN
         aws-region: us-east-1  # Modify the region as needed

      
      - name: Deploy to S3
        run: |
          aws s3 sync build/ s3://dev-static-website-12345/ --delete
